import type {Metadata} from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="container mx-auto p-4">{children}</main>
    );
}
